<a href="https://colab.research.google.com/github/kestrel677/Supervised-Machine-learning-/blob/main/Logistic_Regression77.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Loan Prediction logistic Regression model**

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split

In [4]:
df = pd.read_csv("/data.csv")
df

,Unnamed: 0.1,Unnamed: 0,loan_status,Principal,terms,effective_date,due_date,age,education,Gender
0,0,0,PAIDOFF,1000,30,9/8/2016,10/7/2016,45,High School or Below,male
1,2,2,PAIDOFF,1000,30,9/8/2016,10/7/2016,33,Bechalor,female
2,3,3,PAIDOFF,1000,15,9/8/2016,9/22/2016,27,college,male
3,4,4,PAIDOFF,1000,30,9/9/2016,10/8/2016,28,college,female
4,6,6,PAIDOFF,1000,30,9/9/2016,10/8/2016,29,college,male
...,...,...,...,...,...,...,...,...,...,...
341,394,394,COLLECTION,800,15,9/11/2016,9/25/2016,32,High School or Below,male
342,395,395,COLLECTION,1000,30,9/11/2016,10/10/2016,25,High School or Below,male
343,397,397,COLLECTION,800,15,9/12/2016,9/26/2016,39,college,male
344,398,398,COLLECTION,1000,30,9/12/2016,11/10/2016,28,college,male
345,399,399,COLLECTION,1000,30,9/12/2016,10/11/2016,26,college,male

In [5]:
df.shape

(346, 10)

In [6]:
df.dtypes

Unnamed: 0.1       int64
Unnamed: 0         int64
loan_status       object
Principal          int64
terms              int64
effective_date    object
due_date          object
age                int64
education         object
Gender            object
dtype: object

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 346 entries, 0 to 345
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0.1    346 non-null    int64
 1   Unnamed: 0      346 non-null    int64
 2   loan_status     346 non-null    object
 3   Principal       346 non-null    int64
 4   terms           346 non-null    int64
 5   effective_date  346 non-null    object
 6   due_date        346 non-null    object
 7   age             346 non-null    int64
 8   education       346 non-null    object
 9   Gender          346 non-null    object
dtypes: int64(5), object(5)
memory usage: 27.2+ KB

In [8]:
df.describe()

       Unnamed: 0.1  Unnamed: 0    Principal       terms         age
count    346.000000  346.000000   346.000000  346.000000  346.000000
mean     202.167630  202.167630   943.641618   22.653179   30.939306
std      115.459715  115.459715   109.425530    7.991006    6.039418
min        0.000000    0.000000   300.000000    7.000000   18.000000
25%      107.250000  107.250000   900.000000   15.000000   27.000000
50%      204.500000  204.500000  1000.000000   30.000000   30.000000
75%      298.750000  298.750000  1000.000000   30.000000   35.000000
max      399.000000  399.000000  1000.000000   30.000000   51.000000

In [9]:
df.isnull().sum()

Unnamed: 0.1      0
Unnamed: 0        0
loan_status       0
Principal         0
terms             0
effective_date    0
due_date          0
age               0
education         0
Gender            0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [13]:
num_cols = df.select_dtypes(include=['int64', 'float64'])

In [16]:
import pandas as pd

outlier_df = pd.DataFrame(list(  outlier_summary.items()),
                         columns=['Column', 'Outlier_Count'])

outlier_df = outlier_df.sort_values(by='Outlier_Count', ascending=False)

print(outlier_df)

         Column  Outlier_Count
2     Principal              5
4           age              4
0  Unnamed: 0.1              0
1    Unnamed: 0              0
3         terms              0

In [ ]:
df["hour"] = df["timestamp"].dt.hour
df["day"] = df["timestamp"].dt.day
df["month"] = df["timestamp"].dt.month
df["day_of_week"] = df["timestamp"].dt.dayofweek

In [ ]:
# DROP RAW TIMESTAMP
df.drop(columns=["timestamp"], inplace=True)

In [ ]:
# DROP HIGH CARDINALITY IDS
df.drop(columns=[
    "transaction_id",
    "sender_account",
    "receiver_account",
    "device_hash",
    "ip_address"
], inplace=True)

In [ ]:
outlier_df['Percentage'] = (outlier_df['Outlier_Count'] / len(df)) * 100

print(outlier_df)

In [ ]:
for col in num_cols:
    plt.figure()
    sns.boxplot(x=df[col])
    plt.title(col)
    plt.show()

In [ ]:
cols_to_cap = [
    'amount',
    'is_first_transaction',
    'time_since_last_transaction',
    'spending_deviation_score',
]

for col in cols_to_cap:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df[col] = df[col].clip(lower, upper)

In [ ]:
for col in num_cols:
    plt.figure()
    sns.boxplot(x=df[col])
    plt.title(col)
    plt.show()

In [ ]:
nominal_cols = ["transaction_type","merchant_category","device_used","payment_channel","location"]
df = pd.get_dummies(df,columns=nominal_cols,drop_first=True)

In [ ]:
df["is_fraud"] = df["is_fraud"].astype(int)
# df["is_fraud"] = df["is_fraud"].map({
#     "No": 0,
#     "Yes": 1
# })

In [ ]:
df.dtypes

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Features & target
X = df.drop('is_fraud', axis=1)
y = df['is_fraud']

# Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Select numeric columns
num_cols = X_train.select_dtypes(include=['int64', 'float64']).columns

# Scaling
scaler = StandardScaler()

X_train[num_cols] = scaler.fit_transform(X_train[num_cols])
X_test[num_cols] = scaler.transform(X_test[num_cols])

Logistic Regression is a supervised learning algorithm that uses a linear combination of features passed through a sigmoid function to estimate probabilities for binary classification:

Logistic Regression probability predict karta hai ke data kisi class se belong karta hai ya nahi:

Model ek line draw karta hai jo data ko 2 parts mein divide karti hai, aur phir probability estimate karta hai:

Step 1:

* Weights initialize

Step 2:

* Linear equation calculate

Step 3:

* Sigmoid apply

Step 4:

* Error calculate

Step 5:

* Weights update (Gradient Descent)

1. Input features (x)
        ↓
2. Linear equation (z = wx + b)
        ↓
3. Sigmoid function σ(z)
        ↓
4. Probability (0 to 1)
        ↓
5. Threshold (0.5)
        ↓
6. Class prediction (0 / 1)

In [ ]:
from sklearn.linear_model import LogisticRegression

# model create
log_model = LogisticRegression(max_iter=1000,class_weight="balanced")

# train
log_model.fit(X_train, y_train)

In [ ]:
y_pred = log_model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred))

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

In [ ]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, y_pred))

In [ ]:
y_prob = log_model.predict_proba(X_test)[:, 1]

In [ ]:
from sklearn.metrics import roc_curve

fpr, tpr, thresholds = roc_curve(y_test, y_prob)

In [ ]:
from sklearn.metrics import roc_auc_score

auc_score = roc_auc_score(y_test, y_prob)
print("AUC Score:", auc_score)

In [ ]:
import matplotlib.pyplot as plt

plt.plot(fpr, tpr, label="Logistic Regression")
plt.plot([0,1], [0,1], linestyle='--')  # random line
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.show()